/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "place_dir.h"
#include "bar_anybar.h"
#include "bar_ewmhtags.h"
#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_taglabels.h"
#include "bar_flexwintitle.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "dwmc.h"
#include "floatpos.h"
#include "focusmaster.h"
#include "focusurgent.h"
#include "ipc.h"
#include "ipc/ipc.h"
#include "ipc/util.h"
#include "moveresize.h"
#include "pertag.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "sticky.h"
#include "swallow.h"
#include "tagothermonitor.h"
#include "xrdb.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_gapplessgrid.h"
#include "layout_tile.h"
