/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "place_dir.c"
#include "bar_anybar.c"
#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statusbutton.c"
#include "bar_taglabels.c"
#include "bar_flexwintitle.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "dwmc.c"
#include "floatpos.c"
#include "focusmaster.c"
#include "focusurgent.c"
#include "ipc.c"
#ifdef VERSION
#include "ipc/IPCClient.c"
#include "ipc/yajl_dumps.c"
#include "ipc/ipc.c"
#include "ipc/util.c"
#endif
#include "moveresize.c"
#include "pertag.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "sticky.c"
#include "swallow.c"
#include "tagothermonitor.c"
#include "xrdb.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_gapplessgrid.c"
#include "layout_tile.c"
